### ISSUE TITLE
WRONG REGION ON AREA ENTRY

### ISSUE THREAD

**Issue by caragarpo13** [ppmpme/issues-only#17]
![image](https://user-images.githubusercontent.com/45053162/48522256-87a7d980-e867-11e8-8d65-812f8520d01c.png)

**Comment by mjsolidarios** [comment]
Good day Ma'ams & Sirs. I'm now migrating the database connections for v4 of the system. I'll be able to publish them after school. A preview is now available on http://popcom-dms.herokuapp.com/.
