### ISSUE TITLE
NO AREA ENTRIES IN SOME  POPDEV INDICATORS FOR REGION 2

### ISSUE THREAD

**Issue by POPCOMREGIONII** [ppmpme/issues-only#20]
![issue](https://user-images.githubusercontent.com/45053122/48523307-d92b8500-e8b6-11e8-8da0-d17f6c46d211.PNG)

**Comment by mjsolidarios** [comment]
Thank you po!

**Comment by mjsolidarios** [comment]
Good day Ma'ams & Sirs. I'm now migrating the database connections for v4 of the system. I'll be able to publish them after school. A preview is now available on http://popcom-dms.herokuapp.com/.
