### ISSUE TITLE
AHD: Input: typo error of field title

### ISSUE THREAD

**Issue by region7** [ppmpme/issues-only#24]
![ahd](https://user-images.githubusercontent.com/45053157/48523193-6de1b300-e8b6-11e8-944d-b09b87d88a26.PNG)

**Comment by mjsolidarios** [comment]
Good day Ma'ams & Sirs. I'm now migrating the database connections for v4 of the system. I'll be able to publish them after school. A preview is now available on http://popcom-dms.herokuapp.com/.
