### ISSUE TITLE
ISSUEON PGR REGION2

### ISSUE THREAD

**Issue by POPCOMREGIONII** [ppmpme/issues-only#26]
![issuepgr](https://user-images.githubusercontent.com/45053122/48523491-a33ad080-e8b7-11e8-897b-9d66b113562b.PNG)

**Comment by mjsolidarios** [comment]
Good day Ma'ams & Sirs. I'm now migrating the database connections for v4 of the system. I'll be able to publish them after school. A preview is now available on http://popcom-dms.herokuapp.com/.
