### ISSUE TITLE
Fields has very small space/view for encoding to some indicators that needs value/number

### ISSUE THREAD

**Issue by region7** [ppmpme/issues-only#31]
For encoding efficiency : Fields has very small space/view for encoding to some indicators that needs value/number
suggestion: increase the view of those who needs 3 integers but has only a view of 1 integer when encoding, it only shows after we save the encoded data - if it has an error then the encoder will go back to the encoded data for an edit. For encoding efficiency increase the size of the those fields that needs 3 integers.

**Comment by mjsolidarios** [comment]
Thank you for the suggestion! This will be resolved in version 4.0.

**Comment by mjsolidarios** [comment]
Good day Ma'ams & Sirs. I'm now migrating the database connections for v4 of the system. I'll be able to publish them after school. A preview is now available on http://popcom-dms.herokuapp.com/.
