### ISSUE TITLE
no area entries

### ISSUE THREAD

**Issue by aratpineda** [ppmpme/issues-only#35]

**Comment by aratpineda** [comment]
![image](https://user-images.githubusercontent.com/45053035/48881094-730ea700-ee4e-11e8-8880-815684eeddd1.png)

**Comment by mjsolidarios** [comment]
Thanks for the report @aratpineda! I'm setting the website in maintenance mode for for now to fix the remaining bugs.

**Comment by mjsolidarios** [comment]
Good day Ma'ams & Sirs. I'm now migrating the database connections for v4 of the system. I'll be able to publish them after school. A preview is now available on http://popcom-dms.herokuapp.com/.
