### ISSUE TITLE
Can't open the PPMP M and E online system.

### ISSUE THREAD

**Issue by caragarpo13** [ppmpme/issues-only#36]
![image](https://user-images.githubusercontent.com/45053162/50259538-7db55f80-043f-11e9-8f22-2399da5cc795.png)

**Comment by mjsolidarios** [comment]
Thank you for the report and sorry for the inconvenience. I'll be able to fix the problems this weekend.

**Comment by mjsolidarios** [comment]
Link is now working but the system is not yet fully migrated. Will inform you ASAP after its completion. Thank you!

**Comment by caragarpo13** [comment]
Good am sir. We were already able to access the link, but can't log in using our account.

**Comment by mjsolidarios** [comment]
Hmm...that's weird. I'll check later after school.

**Comment by mjsolidarios** [comment]
Hello Ma'ams/Sirs sorry for the late update. I'll be available again this Friday to resolve this issue.

**Comment by mjsolidarios** [comment]
Good day Ma'ams & Sirs. I'm now migrating the database connections for v4 of the system. I'll be able to publish them after school. A preview is now available on http://popcom-dms.herokuapp.com/.
