### ISSUE TITLE
Log-in error for MIMAROPA Region

### ISSUE THREAD

**Issue by sharmainericardo** [ppmpme/issues-only#39]
Please see screenshot below po for the error encountered when trying to log-in.

![image](https://user-images.githubusercontent.com/45053038/55316930-0c576500-54a2-11e9-8b4e-dda32de8b9da.JPG)

Thank you po.

**Comment by mjsolidarios** [comment]
Issue acknowledged po. ricardomhaine@yahoo.com.ph is now added to the system. Please use 1q2w3e4r5t6y as your default password.
